-- REAL(float4) 은 유효숫자 약 7자리라 지수 가격·거래량이 저장 시 깎인다 (#219).
ALTER TABLE stock_candles
    ALTER COLUMN open TYPE DOUBLE PRECISION,
    ALTER COLUMN high TYPE DOUBLE PRECISION,
    ALTER COLUMN low TYPE DOUBLE PRECISION,
    ALTER COLUMN close TYPE DOUBLE PRECISION,
    ALTER COLUMN volume TYPE DOUBLE PRECISION;

ALTER TABLE stock_analysis_results
    ALTER COLUMN total_score TYPE DOUBLE PRECISION,
    ALTER COLUMN confidence TYPE DOUBLE PRECISION,
    ALTER COLUMN price TYPE DOUBLE PRECISION,
    ALTER COLUMN change TYPE DOUBLE PRECISION,
    ALTER COLUMN change_rate TYPE DOUBLE PRECISION;

ALTER TABLE stock_weekly_expected_moves
    ALTER COLUMN expected_move_high TYPE DOUBLE PRECISION,
    ALTER COLUMN expected_move_low TYPE DOUBLE PRECISION,
    ALTER COLUMN expected_move_pct TYPE DOUBLE PRECISION;
