-- V38: 매수·매도 점수 신호를 50/200 골든·데드크로스 추세 상태로 교체 (#251)
-- 10년 백테스트에서 지표 점수 신호는 예측력이 없었다. 다기간(1W/1M) 분석과 신호 이력도 함께 정리한다.

DELETE FROM stock_analysis_results WHERE timeframe <> '1D';

ALTER TABLE stock_analysis_results
    DROP COLUMN signal,
    DROP COLUMN total_score,
    DROP COLUMN confidence,
    DROP COLUMN market_regime,
    DROP COLUMN technical_scores,
    ADD COLUMN trend       TEXT NOT NULL DEFAULT 'UNKNOWN',
    ADD COLUMN trend_since DATE,
    ADD COLUMN candle_date DATE;

DROP TABLE stock_analysis_history;

-- 나스닥 100 구성 종목(2026-10-07 Nasdaq 공식 목록) 중 기존 관심종목에 없는 85개. GOOG 는 GOOGL 과 같은 회사라 제외.
-- 같은 티커의 활성 행이 있으면 건너뛴다 (idx_stock_watchlist_ticker).
INSERT INTO stock_watchlist (ticker, exchange, name, is_active, "group")
VALUES
    ('ABNB',  'NAS', 'Airbnb',                          TRUE, 'individual'),
    ('ADBE',  'NAS', 'Adobe',                           TRUE, 'individual'),
    ('ADI',   'NAS', 'Analog Devices',                  TRUE, 'individual'),
    ('ADP',   'NAS', 'Automatic Data Processing',       TRUE, 'individual'),
    ('ADSK',  'NAS', 'Autodesk',                        TRUE, 'individual'),
    ('AEP',   'NAS', 'American Electric Power',         TRUE, 'individual'),
    ('ALAB',  'NAS', 'Astera Labs',                     TRUE, 'individual'),
    ('ALNY',  'NAS', 'Alnylam Pharmaceuticals',         TRUE, 'individual'),
    ('AMAT',  'NAS', 'Applied Materials',               TRUE, 'individual'),
    ('AMGN',  'NAS', 'Amgen',                           TRUE, 'individual'),
    ('APP',   'NAS', 'AppLovin',                        TRUE, 'individual'),
    ('ARM',   'NAS', 'Arm Holdings ADR',                TRUE, 'individual'),
    ('ASML',  'NAS', 'ASML Holding ADR',                TRUE, 'individual'),
    ('AXON',  'NAS', 'Axon Enterprise',                 TRUE, 'individual'),
    ('BKNG',  'NAS', 'Booking Holdings',                TRUE, 'individual'),
    ('BKR',   'NAS', 'Baker Hughes',                    TRUE, 'individual'),
    ('CCEP',  'NAS', 'Coca-Cola Europacific Partners',  TRUE, 'individual'),
    ('CDNS',  'NAS', 'Cadence Design Systems',          TRUE, 'individual'),
    ('CEG',   'NAS', 'Constellation Energy',            TRUE, 'individual'),
    ('CMCSA', 'NAS', 'Comcast',                         TRUE, 'individual'),
    ('COST',  'NAS', 'Costco Wholesale',                TRUE, 'individual'),
    ('CPRT',  'NAS', 'Copart',                          TRUE, 'individual'),
    ('CRWD',  'NAS', 'CrowdStrike',                     TRUE, 'individual'),
    ('CRWV',  'NAS', 'CoreWeave',                       TRUE, 'individual'),
    ('CSCO',  'NAS', 'Cisco Systems',                   TRUE, 'individual'),
    ('CSX',   'NAS', 'CSX',                             TRUE, 'individual'),
    ('CTAS',  'NAS', 'Cintas',                          TRUE, 'individual'),
    ('DASH',  'NAS', 'DoorDash',                        TRUE, 'individual'),
    ('DDOG',  'NAS', 'Datadog',                         TRUE, 'individual'),
    ('DXCM',  'NAS', 'DexCom',                          TRUE, 'individual'),
    ('EXC',   'NAS', 'Exelon',                          TRUE, 'individual'),
    ('FANG',  'NAS', 'Diamondback Energy',              TRUE, 'individual'),
    ('FAST',  'NAS', 'Fastenal',                        TRUE, 'individual'),
    ('FER',   'NAS', 'Ferrovial',                       TRUE, 'individual'),
    ('FTNT',  'NAS', 'Fortinet',                        TRUE, 'individual'),
    ('GEHC',  'NAS', 'GE HealthCare Technologies',      TRUE, 'individual'),
    ('GILD',  'NAS', 'Gilead Sciences',                 TRUE, 'individual'),
    ('HON',   'NAS', 'Honeywell International',         TRUE, 'individual'),
    ('HONA',  'NAS', 'Honeywell Aerospace',             TRUE, 'individual'),
    ('IDXX',  'NAS', 'IDEXX Laboratories',              TRUE, 'individual'),
    ('INTU',  'NAS', 'Intuit',                          TRUE, 'individual'),
    ('ISRG',  'NAS', 'Intuitive Surgical',              TRUE, 'individual'),
    ('KDP',   'NAS', 'Keurig Dr Pepper',                TRUE, 'individual'),
    ('KLAC',  'NAS', 'KLA',                             TRUE, 'individual'),
    ('LIN',   'NAS', 'Linde',                           TRUE, 'individual'),
    ('LITE',  'NAS', 'Lumentum',                        TRUE, 'individual'),
    ('LRCX',  'NAS', 'Lam Research',                    TRUE, 'individual'),
    ('MAR',   'NAS', 'Marriott International',          TRUE, 'individual'),
    ('MCHP',  'NAS', 'Microchip Technology',            TRUE, 'individual'),
    ('MDLZ',  'NAS', 'Mondelez International',          TRUE, 'individual'),
    ('MELI',  'NAS', 'MercadoLibre',                    TRUE, 'individual'),
    ('MNST',  'NAS', 'Monster Beverage',                TRUE, 'individual'),
    ('MPWR',  'NAS', 'Monolithic Power Systems',        TRUE, 'individual'),
    ('MRVL',  'NAS', 'Marvell Technology',              TRUE, 'individual'),
    ('MU',    'NAS', 'Micron Technology',               TRUE, 'individual'),
    ('NBIS',  'NAS', 'Nebius Group',                    TRUE, 'individual'),
    ('NXPI',  'NAS', 'NXP Semiconductors',              TRUE, 'individual'),
    ('ODFL',  'NAS', 'Old Dominion Freight Line',       TRUE, 'individual'),
    ('ORLY',  'NAS', 'O''Reilly Automotive',            TRUE, 'individual'),
    ('PANW',  'NAS', 'Palo Alto Networks',              TRUE, 'individual'),
    ('PAYX',  'NAS', 'Paychex',                         TRUE, 'individual'),
    ('PCAR',  'NAS', 'PACCAR',                          TRUE, 'individual'),
    ('PDD',   'NAS', 'PDD Holdings ADR',                TRUE, 'individual'),
    ('PEP',   'NAS', 'PepsiCo',                         TRUE, 'individual'),
    ('PYPL',  'NAS', 'PayPal',                          TRUE, 'individual'),
    ('QCOM',  'NAS', 'Qualcomm',                        TRUE, 'individual'),
    ('REGN',  'NAS', 'Regeneron Pharmaceuticals',       TRUE, 'individual'),
    ('ROP',   'NAS', 'Roper Technologies',              TRUE, 'individual'),
    ('ROST',  'NAS', 'Ross Stores',                     TRUE, 'individual'),
    ('SBUX',  'NAS', 'Starbucks',                       TRUE, 'individual'),
    ('SHOP',  'NAS', 'Shopify',                         TRUE, 'individual'),
    ('SNDK',  'NAS', 'Sandisk',                         TRUE, 'individual'),
    ('SNPS',  'NAS', 'Synopsys',                        TRUE, 'individual'),
    ('SPCX',  'NAS', 'SpaceX',                          TRUE, 'individual'),
    ('STX',   'NAS', 'Seagate Technology',              TRUE, 'individual'),
    ('TER',   'NAS', 'Teradyne',                        TRUE, 'individual'),
    ('TMUS',  'NAS', 'T-Mobile US',                     TRUE, 'individual'),
    ('TRI',   'NAS', 'Thomson Reuters',                 TRUE, 'individual'),
    ('TTWO',  'NAS', 'Take-Two Interactive',            TRUE, 'individual'),
    ('TXN',   'NAS', 'Texas Instruments',               TRUE, 'individual'),
    ('VRTX',  'NAS', 'Vertex Pharmaceuticals',          TRUE, 'individual'),
    ('WDAY',  'NAS', 'Workday',                         TRUE, 'individual'),
    ('WDC',   'NAS', 'Western Digital',                 TRUE, 'individual'),
    ('WMT',   'NAS', 'Walmart',                         TRUE, 'individual'),
    ('XEL',   'NAS', 'Xcel Energy',                     TRUE, 'individual')
ON CONFLICT DO NOTHING;
